解决报错ValueError
运行时报错：
ValueError: Cannot feed value of shape (32, 1, 28, 28) for Tensor `conv2d_23_input:0`, which has shape `(64, 1, 28, 28)`

因为数据集的长度要是batch_size的整数倍，或者把这个改成batch_input_shape=(None,28, 28,1)就可以了